#!/usr/bin/env sh

limelight -m config width 5
limelight -m config radius 13
limelight -m config placement exterior
limelight -m config active_color 0xF01150BB
limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded.."
