#!/usr/bin/env sh

limelight -m config width 4
limelight -m config radius 10
limelight -m config placement exterior
limelight -m config active_color 0xEE11CC11 
limelight -m config normal_color 0xFF000088

echo "limelight configuration loaded.."
